### ISSUE TITLE
📦 Epic: All-in-one releases 

### ISSUE THREAD

**Issue by snvfk1n** [Brucheion/Brucheion#28]
The Brucheion codebase and tooling recently grew in complexity due to a demand in new features. This makes asking users to build Brucheion themselves more difficult. With CI-generated self-contained builds, we can publish new versions that are easily installed. Adding self-updating capabilities to Brucheion will help in distributing these versions quickly to users.

### To-do

* [x] Create self-contained Go binary builds with static assets included (#30)
* [x] Add automated CI tests, generate release builds, and add these to GitHub releases (#33)
* [x] Add client-side updating capabilities via GitHub releases (#42)
* [ ] Properly sign/notarize macOS binaries

**Comment by falafeljan** [comment]
Previous comment on the issues with self-building Brucheion right now: The growing complexity in tooling.

> with additional static assets and build dependencies due to new, interactive UI parts (#26), updating and developing the app becomes more complicated for users. i identify 2 critical steps when building Brucheion right now:
> 
> 1. the additional requirement of installing Node.js
> 2. using `make`, which requires additional software on Windows
> 
> i want to throw in two possible alternatives to the current approach (i advocate for the second one):
> 
> <details>
> <summary>1. using docker 🐳</summary>
> by using docker, we would need to a smaller amount of changes to the current architecture: all static assets would be included in the docker image, which would be created for each platform (macOS, Windows) and then distributed via GitHub Packages.
> 
> users would need to move their library (`user.db`, `cex/`, `image_archive/`) to some permanent location (e.g., `~/Documents/Brucheion/cex`, `~/Documents/Brucheion/library`) and would need to use docker in order to update the image (e.g., running `docker pull ...` via the terminal).
> </details>
> 
> <details>
> <summary>2. using pkger 📦</summary>
> 
> [pkger](https://github.com/markbates/pkger) allows to embed static files into a Go binary by encoding directories directly into a generated Go source file. during runtime, an `os`-compliant API can access these files. with that approach, we could achieve a similar solution to the above way of using docker, but users would just need to replace their Brucheion binary.
> 
> similar to above, user-related data could reside in a permanent place such as `~/Documents/Brucheion/`). using a HTTP framework such as the `http` lib or Gin, we could mount the internal assets as well as the user-provided data as static files.
> 
> release distribution could happen via CI-automated builds per release (Git tag) and subsequently sending the resulting OS-related binary. solutions such as [`go-update`](https://github.com/tj/go-update) could even provide auto-updating capabilities to these single-binary releases.
> </details>

**Comment by jankaszel** [comment]
@ThomasK81 did you make any progress on application signing/notarization?
